project:
  type: website
  title: "Analytics & Big Data"
  output-dir: _site
  # post-render: "bash scripts/decktape.sh"

metadata-files:
  - course.yml

execute:
  cache: true
  freeze: auto

website:
  favicon: assets/favicon.ico
  title: "Analytics & Big Data"
  site-url: https://fs-ise.github.io/analytics-and-big-data/
  repo-url: https://github.com/fs-ise/analytics-and-big-data
  repo-actions: [edit, issue]
  sidebar:
    logo: assets/big-data-analytics-logo.png
    logo-alt: "Analytics & Big Data"
    style: docked
    search: true
    contents:
      - text: Home
        href: index.qmd
      - text: Syllabus
        href: syllabus.qmd
      - text: Group work
        href: group_work.qmd
      - text: Teaching notes
        href: teaching_notes.qmd
      - text: Preparation
        href: preparation.qmd
      - text: Evaluations
        href: evaluations.qmd
      - text: News
        href: news.qmd

format:
  html:
    toc: false
    number-sections: false
    css: assets/styles.css
    include-after-body: assets/repo-actions-bottom.html

bibliography: references.bib
csl: assets/apa.csl

filters:
  - custom-callout

custom-callout:
  resource:
    title: "Resource"
    icon: true
    icon-symbol: "🔗"
    color: "#0d6efd"
  confidential:
    title: "Confidential"
    icon: true
    icon-symbol: "🔒"
    color: "#dc3545"
  objective:
    title: "Objective"
    icon: true
    icon-symbol: "🎯"
    color: "#0d6efd"
  self-service:
    title: "Self-service"
    icon: true
    icon-symbol: "🛠️"
    color: "#198754"
