project:
  type: website
  title: "Analytics & Big Data"
  output-dir: _site
  # post-render: "bash scripts/decktape.sh"

website:

  site-url: https://fs-ise.github.io/big-data-analytics/
  repo-url: https://github.com/fs-ise/big-data-analytics
  repo-actions: [edit, issue]
  navbar:
    right:
      - text: "Overview"
        href: index.qmd
      - text: "Group work"
        href: group_work.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "⚠️ Preparation"
        href: preparation.qmd


format:
  revealjs:
    author: "Prof. Dr. Gerit Wagner"
    theme: simple
    width: 1600
    height: 900
    lazy-load: true
    slide-number: true
    include-before-body: assets/header.html
    template-partials:
      - assets/title-slide.html
    css: [assets/frankfurt.css]
    auto-stretch: false
    slide-level: 2
    title-slide-attributes:
      data-state: "hide-menubar"
    center: false
    section-divs: true
    simplemenu:
      barhtml:
        header: ""
        footer: "<div class='menubar'><ul class='menu'></ul><div class='slide-number'></div></div>"
      scale: 0.67
    mermaid:
      theme: default

bibliography: assets/references.bib
csl: assets/apa.csl


revealjs-plugins:
  - simplemenu

filters:
  - custom-callout


custom-callout:
  resource:
    title: "Resource"
    icon: true
    icon-symbol: "🔗"
    color: "#0d6efd"
  confidential:
    title: "Confidential"
    icon: true
    icon-symbol: "🔒"
    color: "#dc3545"
  objective:
    title: "Objective"
    icon: true
    icon-symbol: "🎯"
    color: "#0d6efd"
  self-service:
    title: "Self-service"
    icon: true
    icon-symbol: "🛠️"
    color: "#198754"