---
title: "News"
format: html
---

<!--
https://datavizsp26.classes.andrewheiss.com/news/
-->


## 2026-05-04 Questions for Exam Preparation

Hi everyone,

Time flies — next week will already be our last session for Analytics & Big Data.

To help prepare for the exam, I would like to invite you to post any questions you would like us to discuss in our final session. These can be questions about specific topics, concepts, readings, assignments, or anything else that would help you prepare.

Please post your questions in the discussion forum here:

https://frankfurtschool.instructure.com/courses/19780/discussion_topics/215196

Please post your questions by Thursday night, so I have enough time to review them and structure our discussion accordingly.

Best regards,

Gerit Wagner


## 2026-04-27: Group projects

Dear students,

we are off to a very good start with the group projects. Several groups have already discussed their topics with me and are well on their way.

For those of you who are still looking for a group—especially if you were not able to attend the in-person sessions—please reach out to your fellow students or feel free to contact me via email. I am happy to help facilitate the matching.

Please also note that the project submission is due on May 30, so that you can complete the whole course before moving on to internships or other summer projects.

Best regards

Gerit Wagner

