---
title: "Analytics & Big Data"
subtitle: "Analytics in organizations"
section_label: "Deployment"
session: "Session 10"
date: "2026-05-11"
nocite: |
    @KunzSpohrerHeinzl2025,@OesterreichAntonTeuteberg2022
---


## {data-menu-title="Learning objectives" data-state="hide-menubar"}

<br><br><br><br><br>

::: {.learning-objectives}
- **Explain** the strategic role of data analytics in data-driven organizations.
- **Discuss** the ethical and legal boundaries of data analytics in organizations.
:::

<!--
- **Design** an end-to-end analytics solution aligned with a business problem and governance constraints.
-->

# TODO {data-stack-name="TODO"}


# Level: Industry (TBD)

Competing on analytics
?
https://ide.mit.edu/sites/default/files/publications/2011.12_Brynjolfsson_Hitt_Kim_Strength%20in%20Numbers_302.pdf

# Level: Organization

OesterreichAntonTeuteberg2022

TBD: prepare/anticipate the connection from north-star KPI to quantitative metrics and analytical models?


# Level: Regulation

TBD. but students should have an overview here


# Level: Process

KunzSpohrerHeinzl2025


# Level: Human-AI interaction (?)

Human: Strich/JAIS
AI: XAI



Note: algorithmic management -> part of the group-work session (one example)


## Survey: Session 10 {data-state="hide-menubar"}

<br><br>

::: {style="display:flex; justify-content:center;"}

{{< qrcode "{{< var sessions.session_10.survey_url >}}" width=400 height=400 >}}

:::

<br><br>

[{{< var sessions.session_10.survey_url >}}]({{< var sessions.session_10.survey_url >}})

::: aside
Note: Responses may be analyzed and published in anonymized form.

Please complete the survey before you leave today — thank you 🙏
:::


# References {data-state="hide-menubar"}