project:
  type: website
  output-dir: ../_site/exercises   # base (will be overridden by profiles)
  title: Exercises

filters:
  - assign

jupyter: python3

website:
  title: "Exercises"
  navbar: false
