project:
  type: website
  output-dir: ../_site/exercises   # base (will be overridden by profiles)
  title: Exercises

format:
  html:
    toc: true
    toc-location: left
    number-sections: false
    toc-title: "Contents"

filters:
  - assign

jupyter: python3

website:
  title: "Exercises"
  navbar: false
