project:
  type: website
  output-dir: ../_site/exercises   # base (will be overridden by profiles)
  title: Exercises

bibliography: ../assets/references.bib
csl: ../assets/apa.csl

filters:
  - assign
  - custom-callout

jupyter: python3

website:
  title: "Exercises"
  navbar: false
