<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exercise 4: Regression I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="exercise_4_files/libs/clipboard/clipboard.min.js"></script>
<script src="exercise_4_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="exercise_4_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="exercise_4_files/libs/quarto-html/popper.min.js"></script>
<script src="exercise_4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exercise_4_files/libs/quarto-html/anchor.min.js"></script>
<link href="exercise_4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exercise_4_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exercise_4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exercise_4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exercise_4_files/libs/bootstrap/bootstrap-7f8d28353e1b7aed8a50cdb71f958a5d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercise 4: Regression I</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="task-a1-fit-a-regression-model-with-scikit-learn" class="level2">
<h2 class="anchored" data-anchor-id="task-a1-fit-a-regression-model-with-scikit-learn">Task A1: Fit a regression model with <code>scikit-learn</code></h2>
<div id="d6aae752" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># One-hot encode the department variable</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> pd.get_dummies(df, columns<span class="op">=</span>[<span class="st">"department"</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># drop_first effectively removes the HR department, setting it as the reference level</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Define X (features) and y (target)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that we drop variables that should not be included in the model</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df_model.drop(columns<span class="op">=</span>[<span class="st">"performance"</span>, <span class="st">"name"</span>, <span class="st">"employee_id"</span>, <span class="st">"role"</span>])</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df_model[<span class="st">"performance"</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear regression model</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>model.fit(X, y)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a coefficient table</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"variable"</span>: X.columns,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"coefficient"</span>: model.coef_</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(coef_df)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Intercept:"</span>, model.intercept_)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           variable  coefficient
0        experience     1.817213
1    training_hours     0.913459
2            salary     0.000382
3      remote_share    -0.936416
4         team_size     1.392150
5   manager_quality     5.821155
6     department_IT    13.929535
7  department_Sales    12.758165
Intercept: 45.630943483089595</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><em>Note: The <code>HR</code> department serves as the reference category.</em></p>
</blockquote>
<div style="page-break-after: always;"></div>
</section>
<section id="task-a2-interpret-the-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="task-a2-interpret-the-coefficients">Task A2: Interpret the coefficients</h2>
<ol type="1">
<li>Which variables have a positive association with performance?</li>
</ol>
<p>The variables with a positive association with performance are:</p>
<ul>
<li><code>experience</code></li>
<li><code>training_hours</code></li>
<li><code>salary</code></li>
<li><code>team_size</code></li>
<li><code>manager_quality</code></li>
<li><code>department_IT</code></li>
<li><code>department_Sales</code></li>
</ul>
<p>Their coefficients are all positive, which means that higher values of these variables are associated with higher predicted performance, holding the other variables constant.</p>
<ol start="2" type="1">
<li>Which variables have a negative association with performance?</li>
</ol>
<p>The variable with a negative association with performance is:</p>
<ul>
<li><code>remote_share</code></li>
</ul>
<p>Its coefficient is negative (<code>-0.936</code>), which means that a higher share of remote work is associated with slightly lower predicted performance, holding the other variables constant.</p>
<ol start="3" type="1">
<li>How would you interpret the coefficient of <code>remote_share</code>?</li>
</ol>
<p>The coefficient of <code>remote_share</code> is about <code>-0.94</code>. Because <code>remote_share</code> ranges from 0 to 1, this means:</p>
<ul>
<li>moving from fully on-site (<code>0</code>) to fully remote (<code>1</code>) is associated with a decrease of about <code>0.94</code> points in predicted performance, holding the other variables constant.</li>
</ul>
<p>A smaller change is often easier to interpret in practice. For example:</p>
<ul>
<li>an increase of <code>0.10</code> in <code>remote_share</code> (10 percentage points more remote work) is associated with a decrease of about <code>0.094</code> performance points.</li>
</ul>
<ol start="4" type="1">
<li>Is the <code>remote_share</code> effect large or small in practical terms?</li>
</ol>
<p>The effect appears to be small in practical terms.</p>
<p>Even a very large change in remote work share—from fully on-site to fully remote—is associated with less than one point lower predicted performance (<code>-0.94</code>). For a more realistic change of 10 percentage points, the predicted difference is only about <code>-0.094</code> points.</p>
<p>Compared with other coefficients, especially <code>manager_quality</code> (<code>5.82</code>) or the department coefficients (<code>about 13</code> to <code>14</code>), the <code>remote_share</code> effect is relatively small.</p>
<ol start="5" type="1">
<li>How should dummy variables such as <code>department_IT</code> or <code>department_Sales</code> be interpreted?</li>
</ol>
<p>Dummy variables compare one category to the omitted reference category.</p>
<p>Here, <code>department_IT</code> and <code>department_Sales</code> show how those departments differ from the reference department, which is the department that was dropped during one-hot encoding. If <code>drop_first=True</code> was used and the departments are ordered alphabetically, the reference category is <code>HR</code>.</p>
<p>This means:</p>
<ul>
<li><code>department_IT = 13.93</code> suggests that employees in IT have, on average, about <code>13.93</code> points higher predicted performance than employees in the reference department, holding all other variables constant.</li>
<li><code>department_Sales = 12.76</code> suggests that employees in Sales have, on average, about <code>12.76</code> points higher predicted performance than employees in the reference department, again holding other variables constant.</li>
</ul>
<p>These coefficients do not compare IT directly with Sales. Each is compared to the reference department.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="part-b-regression-tables-with-statsmodels" class="level1">
<h1>Part B — Regression tables with <code>statsmodels</code> <a id="statsmodels" href=""></a></h1>
<section id="task-b1-estimate-the-same-model-with-statsmodels" class="level2">
<h2 class="anchored" data-anchor-id="task-b1-estimate-the-same-model-with-statsmodels">Task B1: Estimate the same model with <code>statsmodels</code></h2>
<div id="a9890a23" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the regression model using a formula</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>model_sm <span class="op">=</span> smf.ols(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    formula<span class="op">=</span><span class="st">"performance ~ experience + training_hours + salary + remote_share + team_size + manager_quality + C(department)"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>df</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>).fit()</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the regression table</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_sm.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:            performance   R-squared:                       0.816
Model:                            OLS   Adj. R-squared:                  0.814
Method:                 Least Squares   F-statistic:                     768.8
Date:                Wed, 15 Apr 2026   Prob (F-statistic):               0.00
Time:                        15:12:55   Log-Likelihood:                -5207.8
No. Observations:                1400   AIC:                         1.043e+04
Df Residuals:                    1391   BIC:                         1.048e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 45.6309      2.397     19.035      0.000      40.928      50.334
C(department)[T.IT]       13.9295      0.770     18.093      0.000      12.419      15.440
C(department)[T.Sales]    12.7582      0.730     17.465      0.000      11.325      14.191
experience                 1.8172      0.116     15.671      0.000       1.590       2.045
training_hours             0.9135      0.027     33.517      0.000       0.860       0.967
salary                     0.0004    5.4e-05      7.064      0.000       0.000       0.000
remote_share              -0.9364      1.238     -0.757      0.449      -3.364       1.491
team_size                  1.3921      0.077     18.036      0.000       1.241       1.544
manager_quality            5.8212      0.224     25.982      0.000       5.382       6.261
==============================================================================
Omnibus:                        0.442   Durbin-Watson:                   1.996
Prob(Omnibus):                  0.802   Jarque-Bera (JB):                0.414
Skew:                           0.042   Prob(JB):                        0.813
Kurtosis:                       3.010   Cond. No.                     4.76e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.76e+05. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="task-b2-interpret-the-regression-table" class="level2">
<h2 class="anchored" data-anchor-id="task-b2-interpret-the-regression-table">Task B2: Interpret the regression table</h2>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions:</h3>
<ol type="1">
<li><strong>Compare coefficients</strong> Are the coefficient estimates (e.g., for <code>remote_share</code>) similar to those from <code>scikit-learn</code>?</li>
</ol>
<p>Yes, the coefficients are the same (up to rounding). Both libraries estimate the same model on the same data, so we expect identical results.</p>
<ol start="2" type="1">
<li><strong>Understanding statistical significance</strong> Which variables are statistically significant based on the p-values? How does this additional information change (or not change) your interpretation from Part A?</li>
</ol>
<p>All variables except <code>remote_share</code> are statistically significant (p &lt; 0.05).</p>
<p>This adds to Part A: although <code>remote_share</code> has a negative coefficient, it is not statistically reliable.</p>
<ol start="3" type="1">
<li><strong>Interpreting <code>remote_share</code> more formally</strong> What do the p-value and confidence interval suggest about the reliability of the <code>remote_share</code> effect?</li>
</ol>
<p>The p-value (0.449) is high and the confidence interval includes 0.</p>
<p>This suggests that the effect of <code>remote_share</code> is uncertain and not statistically significant.</p>
<ol start="4" type="1">
<li><strong>Model fit and explanatory power</strong> What do R² and adjusted R² tell you about how well the model explains performance? Why should we be cautious when interpreting these values?</li>
</ol>
<p>R² ≈ 0.82 means the model explains a large share of variation in performance.</p>
<p>However, a high R² does not guarantee that the model is correct or that effects are causal.</p>
<ol start="5" type="1">
<li><p><strong>Comparing workflows: <code>scikit-learn</code> vs.&nbsp;<code>statsmodels</code></strong> Reflect on how the model was specified in both parts:</p>
<ul>
<li>How did you define variables and transformations in <code>scikit-learn</code>?</li>
<li>How does the <strong>formula interface</strong> in <code>statsmodels</code> simplify (or change) this process?</li>
<li>What are the advantages of using a formula like <code>performance ~ remote_share + ...</code>?</li>
</ul></li>
</ol>
<p>In <code>scikit-learn</code>, we manually prepared data (e.g., dummy variables, X/y).</p>
<p>In <code>statsmodels</code>, the formula (<code>performance ~ ... + C(department)</code>) simplifies this.</p>
<p>The formula approach is more readable and better suited for interpretation.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="part-c-regression-diagnostics" class="level1">
<h1>Part C — Regression diagnostics <a id="diagnostics" href=""></a></h1>
<section id="task-c1-residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="task-c1-residual-plot">Task C1: Residual plot</h2>
<p>Create a simple residual plot for the fitted <code>scikit-learn</code> model from part A.</p>
<div id="ef055fe7" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>residuals <span class="op">=</span> y <span class="op">-</span> model.predict(X)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(model.predict(X), residuals)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted performance"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual plot"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise_4_files/figure-html/cell-9-output-1.png" width="596" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Questions:</p>
<ol type="1">
<li>Do the residuals look roughly random?</li>
</ol>
<p>Yes, the residuals appear to be randomly scattered around zero.</p>
<p>This suggests that the linear model is a reasonable approximation of the relationship in the data.</p>
<ol start="2" type="1">
<li>Do you see patterns that may indicate model problems?</li>
</ol>
<p>No clear patterns are visible (e.g., no curvature or systematic structure).</p>
<p>This indicates that there are no obvious signs of model misspecification based on this plot.</p>
<ol start="3" type="1">
<li>What would a clear funnel shape suggest?</li>
</ol>
<p>A funnel shape would suggest <strong>heteroscedasticity</strong>, meaning that the variance of the residuals changes with the predicted values.</p>
<p>This would violate a key regression assumption (constant variance) and could make standard errors and statistical tests unreliable.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="part-d-subgroup-analysis-does-one-model-fit-all-departments" class="level1">
<h1>Part D — Subgroup analysis: does one model fit all departments? <a id="subgroup-analysis" href=""></a></h1>
<section id="task-d1-department-specific-regressions" class="level2">
<h2 class="anchored" data-anchor-id="task-d1-department-specific-regressions">Task D1: Department-specific regressions</h2>
<p>Estimate separate regressions for <code>Sales</code>, <code>IT</code>, and <code>HR</code>.</p>
<div id="428af631" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {}</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dept <span class="kw">in</span> df[<span class="st">"department"</span>].unique():</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Subset data for one department</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    df_sub <span class="op">=</span> df[df[<span class="st">"department"</span>] <span class="op">==</span> dept].copy()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define X and y</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    X_sub <span class="op">=</span> df_sub[</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        [<span class="st">"experience"</span>, <span class="st">"training_hours"</span>, <span class="st">"salary"</span>, <span class="st">"remote_share"</span>, <span class="st">"team_size"</span>, <span class="st">"manager_quality"</span>]</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    y_sub <span class="op">=</span> df_sub[<span class="st">"performance"</span>]</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add constant and fit OLS model</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    X_sub <span class="op">=</span> sm.add_constant(X_sub)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    model_sub <span class="op">=</span> sm.OLS(y_sub, X_sub).fit()</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store result</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    results[dept] <span class="op">=</span> model_sub</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">=== Regression results for </span><span class="sc">{</span>dept<span class="sc">}</span><span class="ss"> ==="</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(model_sub.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=== Regression results for Sales ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            performance   R-squared:                       0.806
Model:                            OLS   Adj. R-squared:                  0.804
Method:                 Least Squares   F-statistic:                     392.3
Date:                Wed, 15 Apr 2026   Prob (F-statistic):          5.90e-198
Time:                        15:12:56   Log-Likelihood:                -2099.4
No. Observations:                 573   AIC:                             4213.
Df Residuals:                     566   BIC:                             4243.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              66.1880      3.317     19.956      0.000      59.674      72.702
experience          2.0658      0.165     12.540      0.000       1.742       2.389
training_hours      0.8965      0.040     22.636      0.000       0.819       0.974
salary              0.0003   7.61e-05      3.518      0.000       0.000       0.000
remote_share       -2.9166      1.841     -1.584      0.114      -6.533       0.700
team_size           1.3468      0.112     12.048      0.000       1.127       1.566
manager_quality     4.9809      0.334     14.910      0.000       4.325       5.637
==============================================================================
Omnibus:                        0.995   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.608   Jarque-Bera (JB):                0.973
Skew:                           0.101   Prob(JB):                        0.615
Kurtosis:                       2.986   Cond. No.                     4.47e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.47e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

=== Regression results for HR ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            performance   R-squared:                       0.786
Model:                            OLS   Adj. R-squared:                  0.782
Method:                 Least Squares   F-statistic:                     173.0
Date:                Wed, 15 Apr 2026   Prob (F-statistic):           1.88e-91
Time:                        15:12:56   Log-Likelihood:                -1072.5
No. Observations:                 289   AIC:                             2159.
Df Residuals:                     282   BIC:                             2185.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              47.2129      5.419      8.712      0.000      36.545      57.880
experience          1.3588      0.272      4.997      0.000       0.824       1.894
training_hours      0.9066      0.066     13.811      0.000       0.777       1.036
salary              0.0006      0.000      4.519      0.000       0.000       0.001
remote_share       -6.4131      2.890     -2.219      0.027     -12.101      -0.725
team_size           1.3288      0.173      7.665      0.000       0.988       1.670
manager_quality     4.7151      0.477      9.888      0.000       3.776       5.654
==============================================================================
Omnibus:                        2.090   Durbin-Watson:                   1.917
Prob(Omnibus):                  0.352   Jarque-Bera (JB):                2.159
Skew:                          -0.179   Prob(JB):                        0.340
Kurtosis:                       2.774   Cond. No.                     4.75e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.75e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

=== Regression results for IT ===
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            performance   R-squared:                       0.803
Model:                            OLS   Adj. R-squared:                  0.801
Method:                 Least Squares   F-statistic:                     361.3
Date:                Wed, 15 Apr 2026   Prob (F-statistic):          8.13e-184
Time:                        15:12:56   Log-Likelihood:                -2010.0
No. Observations:                 538   AIC:                             4034.
Df Residuals:                     531   BIC:                             4064.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              48.2260      4.059     11.880      0.000      40.252      56.200
experience          1.6694      0.195      8.568      0.000       1.287       2.052
training_hours      0.9113      0.044     20.596      0.000       0.824       0.998
salary              0.0005   9.14e-05      4.962      0.000       0.000       0.001
remote_share        4.0651      2.000      2.033      0.043       0.137       7.993
team_size           1.4581      0.130     11.198      0.000       1.202       1.714
manager_quality     7.4462      0.375     19.867      0.000       6.710       8.182
==============================================================================
Omnibus:                        2.112   Durbin-Watson:                   1.930
Prob(Omnibus):                  0.348   Jarque-Bera (JB):                1.952
Skew:                           0.091   Prob(JB):                        0.377
Kurtosis:                       3.232   Cond. No.                     4.93e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.93e+05. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="task-d2-compare-the-subgroup-models" class="level2">
<h2 class="anchored" data-anchor-id="task-d2-compare-the-subgroup-models">Task D2: Compare the subgroup models</h2>
<p>Use the results to answer the following questions.</p>
<ol type="1">
<li>Do the coefficients differ across departments?</li>
</ol>
<p>Yes, the coefficients differ across departments. While most variables (e.g., experience, training_hours, salary, team_size, manager_quality) are positively associated with performance in all departments, the magnitude of these effects varies.</p>
<p>For example, experience has a stronger effect in Sales than in HR, and manager_quality is much more influential in IT than in the other departments. In contrast, training_hours shows a very similar effect across all departments.</p>
<p>This indicates that the strength of relationships is not constant across departments.</p>
<ol start="2" type="1">
<li>Is <code>remote_share</code> associated with performance in the same way in every department?</li>
</ol>
<p>No, the association differs across departments.</p>
<p>In Sales, remote_share has a negative but not statistically significant effect. In HR, it has a negative and statistically significant effect, suggesting that more remote work is associated with lower performance. In contrast, in IT, the effect is positive and statistically significant.</p>
<p>This shows that remote work impacts performance differently depending on the department.</p>
<ol start="3" type="1">
<li>Does <code>manager_quality</code> seem equally important in all departments?</li>
</ol>
<p>No, although manager_quality is positively and significantly associated with performance in all departments, its importance varies.</p>
<p>The effect is strongest in IT, where the coefficient is substantially larger than in Sales and HR. This suggests that high-quality management may be particularly critical in IT compared to other departments.</p>
<ol start="4" type="1">
<li>What does this tell us about heterogeneity in company data?</li>
</ol>
<p>The results indicate that the data are heterogeneous across departments. The same variables do not have identical effects everywhere, and some relationships (e.g., remote_share) even change direction.</p>
<p>This suggests that departments differ in their work structures, tasks, and coordination needs, leading to different performance drivers.</p>
<ol start="5" type="1">
<li>Why might a single model be too simplistic?</li>
</ol>
<p>A single model assumes that the effects of all variables are the same across departments (apart from intercept differences when using dummies).</p>
<p>However, the subgroup results show that some effects vary in magnitude or even direction. A single model would therefore mask these differences and potentially lead to misleading conclusions.</p>
<p>Using subgroup models or interaction terms can better capture these variations.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Key idea">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Key idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>If relationships differ strongly between groups, a single regression model can hide important structure.</p>
</div>
</div>
</section>
</section>
<section id="part-e-deployment" class="level1">
<h1>Part E — Deployment <a id="deployment" href=""></a></h1>
<p>Saving and loading a model is useful in practice, but it is not the main conceptual focus of this notebook.</p>
<p>Here, it is included as an optional extension after you have already worked through model estimation, interpretation, diagnostics, and subgroup analysis.</p>
<section id="task-e1-optional-save-a-fitted-model" class="level2">
<h2 class="anchored" data-anchor-id="task-e1-optional-save-a-fitted-model">Task E1 (optional): Save a fitted model</h2>
<div id="efbcf3af" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> joblib</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the fitted sklearn model</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>joblib.dump(model, <span class="st">"data/employee_performance_model.joblib"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>['data/employee_performance_model.joblib']</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="task-e2-optional-load-the-model-and-predict-a-new-case" class="level2">
<h2 class="anchored" data-anchor-id="task-e2-optional-load-the-model-and-predict-a-new-case">Task E2 (optional): Load the model and predict a new case</h2>
<div id="7906ec5f" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> joblib</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the saved model</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>loaded_model <span class="op">=</span> joblib.load(<span class="st">"data/employee_performance_model.joblib"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new employee record (must match training data structure)</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>new_employee <span class="op">=</span> pd.DataFrame([</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"experience"</span>: <span class="dv">8</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"training_hours"</span>: <span class="dv">45</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"salary"</span>: <span class="dv">56000</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"remote_share"</span>: <span class="fl">0.4</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"team_size"</span>: <span class="dv">7</span>,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"manager_quality"</span>: <span class="dv">4</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"department_IT"</span>: <span class="dv">1</span>,</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"department_Sales"</span>: <span class="dv">0</span>,</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate prediction</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>prediction <span class="op">=</span> loaded_model.predict(new_employee)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(prediction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[169.22919069]</code></pre>
</div>
</div>
</section>
<section id="task-e3-reflect-on-practical-and-organizational-considerations" class="level2">
<h2 class="anchored" data-anchor-id="task-e3-reflect-on-practical-and-organizational-considerations">Task E3: Reflect on practical and organizational considerations</h2>
<p><strong>Questions:</strong></p>
<ol type="1">
<li>What practical challenges might arise when using this model to support decisions about employees?</li>
</ol>
<ul>
<li>The model may rely on incomplete or imperfect data (e.g., missing relevant factors like motivation or task complexity).</li>
<li>Input data for new predictions must be prepared in exactly the same way (same variables, same encoding).</li>
<li>The model may not generalize well if the company changes (e.g., new work practices or policies).</li>
<li>Interpretation requires care—managers may misread coefficients as causal effects.</li>
</ul>
<ol start="2" type="1">
<li>What risks could emerge if the model is used without careful interpretation or oversight?</li>
</ol>
<ul>
<li>Decisions could be based on misleading relationships (e.g., interpreting correlation as causation).</li>
<li>The model could unintentionally disadvantage certain groups (e.g., departments or work styles).</li>
<li>Overreliance on the model could reduce human judgment and context-sensitive decision-making.</li>
<li>Employees may lose trust if decisions appear opaque or unfair.</li>
</ul>
<ol start="3" type="1">
<li>What steps and safeguards would be important to ensure that the model is used <strong>fairly, transparently, and responsibly</strong>, taking into account legal and organizational requirements (e.g., employee representation, data protection)?</li>
</ol>
<ul>
<li>Ensure <strong>legal compliance from the outset</strong>, especially with data protection regulations (e.g., GDPR) and rules governing employee data and monitoring.</li>
<li>Involve <strong>employee representatives (e.g., works councils)</strong> early in the process, as the use of such models for employee-related decisions may require formal involvement and approval.</li>
<li>Define clearly <strong>how the model will be used</strong> (e.g., decision support vs.&nbsp;automated decisions) and ensure this aligns with legal and organizational guidelines.</li>
<li>Ensure transparency: document how the model works, what data is used, and how results should be interpreted.</li>
<li>Communicate openly with employees to maintain trust and clarify the purpose and limits of the model.</li>
<li>Check for potential bias or unfair effects across groups (e.g., departments) and address them if necessary.</li>
<li>Validate the model regularly and monitor whether it remains appropriate as conditions change.</li>
</ul>
<p>Overall, responsible use requires aligning technical implementation with legal requirements, organizational processes, and ethical considerations.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>