---
title: "Notes: Session 6: Machine learning I"
format: html
---

| Time (min) | Duration | Topic                           | Additional materials |
|------------|----------|---------------------------------|----------------------|
| 0–23       | 23       | Foundations                     |                      |
| 23–46      | 23       | The Generalization Problem      |                      |
| 46–68      | 22       | The Machine Learning Workflow   |                      |
| 68–90      | 22       | Performance                     |                      |

::: callout-note

Note: moved unsupervised ML (clustering) to EDA (mention here only as an example of unsupervised ML)

TODO: suggest code reading/understanding exercises (e.g., "what are the next steps of the procedure?", "annotate what is done in the code blocks", "give pseudo code", "are there any errors (e.g., switched code blocks)?")

Nice introduction:
https://kuleshov-group.github.io/aml-website (careful: copyright!)

Lecture:
https://harvard-iacs.github.io/2019-CS109A/lectures/lecture7/presentation/Lecture7_ModeLSelectionRegularization.pdf

https://github.com/kuleshov/cornell-cs5785-2025-applied-ml/blob/main/lecture-notes/lecture2-supervised-learning.ipynb

https://jose.theoj.org/papers/10.21105/jose.00239
-> slides not useful for ABD
-> Exercises: penguin dataset, but maybe useful as an inspiration.
https://github.com/Cambridge-ICCS/practical-ml-with-pytorch/tree/main/exercises


https://www.3blue1brown.com/topics/neural-networks
-> instructive animations on neural networks etc.

https://www.youtube.com/watch?v=jGwO_UgTS7I
-> Andrew Ng lecture (TODO)
https://cs229.stanford.edu/

:::

## TODO: Group work topics

Check which topics were selected by groups, identify potential overlap and guide topic selection.

## Supervised ML

Add illustration like https://blog.infocruncher.com/2023/02/17/ml-training/
- Classical programming: rules + data -> answers
- Supervised ML: data + answers -> rules

## Bias-Variance tradeoff

Variance: draw many training datasets from the population, train the model on each one, analyze fluctuation in predictions

## Training/Test data

Highlight: tabular data (features in rows). Only for deep learning, unstructured data can be used as an input (learns pattersn automatically)


## Problems with fixed training and test samples

Optimizing the model training: refers to

- Hyperparameter tuning
- Feature engineering decisions
- Model design choices
- Training procedure tweaks

Problem: the test data does not remain "unseen"

“Endogenization of the test data” means that the test set—supposed to be an external, independent benchmark—becomes internally involved in the model-building process.

## Exercises

Feature engineering:
https://www.kaggle.com/learn/feature-engineering

Nice "whats wrong with the procedure":
https://courses.cs.washington.edu/courses/cse446/26sp/schedule/lectures/05-train%20test%20split%20cross%20validation.pdf

Exercises in jupyter:
https://github.com/intro-stat-learning/ISLP_labs/
https://harvard-iacs.github.io/2019-CS109A/labs/lab9/notebook/
