---
title: "Notes: Session 9: Big Data II"
format: html
---

| Time (min) | Duration | Topic | Additional materials |
|------------|----------|-------|----------------------|
| 0–90       | 90       | TODO  |                      |

::: callout-note
TODO


Neural Networks:
https://www.youtube.com/watch?v=aircAruvnKk
https://www.youtube.com/watch?v=IHZwWFHWa-w
https://www.youtube.com/watch?v=Ilg3gGewQ5U


Comprehensive resource (formal specification and implementation): https://d2l.ai/index.html

TBD/whether and where to cover:
Acquire and preprocess large-scale or unstructured data using APIs and appropriate tools in Python.
Apply large language models or other scalable methods to extract, classify, or summarize unstructured data.
TBD: API Keys?!
:::

## Introductory comments

NN : very inspiring class of models and algorithms, which model how nature solves particular problems. NN: brain, but also: genetic algorithms, or ant algorithms for search problems.

Maybe start with something like:
https://web.stanford.edu/~jurafsky/slp3/slides/nn25aug.pdf



## Survey

TODO: ask for areas where additional practice material would be helpful; questions for the exam (prepare for next session)