---
title: "Notes: Session 5: Regression II"
format: html
---

| Time (min) | Duration | Topic                         | Additional materials |
|------------|----------|-------------------------------|----------------------|
| 0–30       | 30       | Refining the model            |                      |
| 30–60      | 30       | Explanation ↔ prediction      |                      |
| 60–90      | 30       | Regression → Machine learning |                      |


::: callout-note

good slides: https://harvard-iacs.github.io/2019-CS109A/lectures/lecture10/ (https://harvard-iacs.github.io/2019-CS109A/lectures/lecture11/presentation/Lecture11_LogReg2.pdf)

good (simple; geographical) explanation:  https://www.youtube.com/watch?v=yIYKR4sgzI8

Lecture, Ng: https://www.youtube.com/watch?v=4u81xU7BIOc

https://web.stanford.edu/class/cme250/files/cme250_lecture2.pdf

https://slds-lmu.github.io/i2ml/chapters/03_supervised_classification/03-04-classification-logistic/

https://ubc-cs.github.io/cpsc330-2023W1/README.html

Optional /extension: changing the data: https://ubc-cs.github.io/cpsc330-2023W1/lectures/09_classification-metrics.html#optional-changing-the-data


https://harvard-iacs.github.io/2019-CS109A/lectures/lecture-11/notebook/
https://github.com/UBC-CS/cpsc330-2023W1
https://slds-lmu.github.io/i2ml/

https://www2.stat.duke.edu/courses/Spring20/sta210.001/labs/lab-08-logistic.html


Goal: Deepen linear regression and surface modeling tensions.

You are not just teaching “more regression.”
You are teaching: How modeling goals shape methodological choices (or how they interact).


Close with a framing slide:
- Analytics is not one method. It is a toolbox shaped by goals.
Then summarize:
- Regression for understanding
- Regression for prediction
- Logistic regression as bridge to ML
And preview:
- Next: more complex machine learning models.


TODO: explicit learning: when we use regression as a baseline, we will also run it in a train/test mode (unlike in exercises 4 and 5)
:::


## Exercise

| Time (min) | Duration | Topic                         | Additional materials |
|------------|----------|-------------------------------|----------------------|
| 0–30       | 30       | Group work assignment         |                      |
| 30–90      | 60       | Logistic regression           |                      |


<!--
        TBD: using forward and backward variable selection?

        ::: {.learning-objectives}
        - Estimate and interpret a multiple regression model in Python.
        - Refine a regression model, assessing how additional predictors affect model fit.
        - Implement and evaluate a logistic regression model for a binary outcome.
        :::

-->