---
title: "Notes: Session 2: Analytical data architecture"
format: html
---

2026-03-30 lecture: 85 minutes (5 min short)

TODO: check for code-based example of ELT/ETL: https://proceedings.scipy.org/articles/wjjm7869

::: callout-note
TODO

Refer to the @Davenport2006 case: competing on analytics requires organizations to go beyond simple descriptive statistics.
As such, traditional DWH may be the (historical) foundation for analytics.

Clarify: OLTP <-> OLAP
OLTP -> ETL -> DWH -> OLAP

Distinguish fact and dimension tables


Learning objective: writing SQL queries!?

Illustrate: OLAP as a "systems approach", notebooks as a more flexible data science approach

Rotating hypercube: similar to rotating in tidy-data preparation?

Extract exercises?

TBD: complete the exercise on paper? provide a PDF version?

<!--
    TODO
    - https://chatgpt.com/c/69bc043b-0440-8396-92d5-78bed59da9d4
    - highlight must-learn/add learning notes
    - skill/practice: correspondence between OLAP and sql: https://chatgpt.com/c/69bc058b-bac8-8393-925a-c5f38ba8b6aa
-->


:::

## Summary/previous lectures

- Rise of analytics: descriptive/predictive/prescriptive, CRISP-DM
- Data preparation: variable types, data quality, structuring (what tools expect), clustering/k-means
- Tech. setup: Jupyter notebooks, Codespaces
-> Almost completed data foundations, will start with modeling next session


## DWH concept

**Subject-oriented (Inmon):**
A DWH is organized around **core business subjects** (e.g., customer, product, sales), which correspond to **facts and dimensions in a star schema**.
Instead of storing data separately across operational systems (e.g., CRM, billing, support), the DWH integrates them into unified subject areas—e.g., a **Customer** view combining purchases, interactions, payments, and demographics.





## Modern analytics

DWH codifies data preparation procedures (all transformations, etc. we covered in the previous lecture), access to databases, metadata-knowledge.
This could make DWH-evolution more efficient for organizations than replacing them with new systems in a greenfield-approach.

Data quality issues could be discussed along DWH/ETL. E.g., transformations are in the transformation phase, incorrect data should be fixed in the source systems, for duplicates it depends (whether they are in or between-dataset duplicates)

Modern ML/analytics applications often operate as a layer on top of a DWH

<!--
::: callout-note
See /home/gerit/workspace/projects/abd/nextcloud/Material/ABD/exercises/Solutions_DW-Modelling.pdf
TODO: existing exercise sheet?
https://github.com/ShantanilBagchi/DataCamp/blob/master/SQL%20Courses/Database%20Design/Solutions.md
https://gitlab.ost.ch/db/datana/-/blob/master/Uebungen/02_DW_OLAP/README.adoc
:::
-->


## Exercise

2026-03-30: 90 minutes (approx. 60 minutes for part 1+2 with discussion; 30 minutes for part 5/1+2; skipped remaining modelling/OLAP/Questions)

TODO: do fact tables require a primary key?
-> can we add the same tuple multiple times?
-> check: is this handled by "artificial primary keys" (built-in)?

TODO: Key question: why should time be a separate table?
- Creating a time dimension table is helpful to trigger database indexing (for efficient OLAP operations)

Part 2: lesson should be "extract time as table" and "integrate" class into wine.
