---
title: "Notes: Session 1: The rise of analytics"
format: html
---

## Lecture

Note: Orga: 20 min

| Time (min)  | Duration  | Topic                         | Additional materials                           |
|-------------|-----------|-------------------------------|------------------------------------------------|
| 20-35       | 15        | More data                     |                                                |
| 35-50       | 15        | More computing power          |                                                |
| 50-65       | 15        | New algorithms                |                                                |
| 65-80       | 15        | New analytics processes       |                                                |

::: objective
In this session, our goal is to explain why modern data analytics is successful, with reference to and examples from the four areas.
:::

Focus on algorithms (enable more elaborate models and analyses)



## Analytical processes

Key trends of improvement:

- Maturing: from descriptive to predictive and prescriptive (reducing ambiguity and the need for human involvement in business decisions)
- Pervasive: extending to different areas (e.g., understanding customers with A/B testing), departments (logistics, financial, ...) with specific disciplines refining more specialized models (forecasting, supply chain, scheduling, queueing, ...)
- Standardized: algorithms and processes are shared and standardized across companies and industries (e.g., ML/LLM; analytics software/environments, governance models like CRIPS-DM) -> intensifies competition

CRISP-DM: most widely used analytics model (https://www.forbes.com/sites/metabrown/2015/07/29/what-it-needs-to-know-about-the-data-mining-process/#2065f3a3515f)



## Exercise

| Time (min) | Duration  | Topic                              | Additional materials                           |
|------------|-----------|------------------------------------|------------------------------------------------|
| 0-30       | 30        | Introduction and setup             |                                                |
| 30-90      | 60        | Data handling in Python            |                                                |

::: objective
Ask students to create a GitHub account (CHECK: free student packs?)

TBD: typical exam questions corresponding to the lecture? -

Explain the Jupyter notebooks, GitHub setup. Mention that students can always use software like Spyder (see Tipps im `Umgang mit Spyder.docx`).

Start in groups of two (random?)

Introduce system (badges) - similar to https://eduki.com/de/material/306565/schilder-fragen-fertig-ich-arbeite
**check classrooms before! - can it be attached to the desks?**


TODO: explicitly address the question why we select Python/jupyter (give an overview of the landscape), argue that Python is challenging (not a low/no-code platform), very popular (supports many analytical use cases), and allows you to quickly learn other tools


:::